#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git branch --show-current)

if [ "$branch" = "main" ]; then
  echo "Direct push to main branch is not allowed."
  exit 1
fi

yarn check:uncommitted && yarn test:cov
